import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { decodeState } from "./decode";

/**
 * Contract test between the C++ encoder (src/viz/wire.cpp) and this decoder.
 *
 * The fixture is NOT committed: it is generated by the real engine binary
 * (`test_viz fixture <path>`) immediately before this runs. So the two sides
 * cannot drift -- rename a field in wire.cpp and this fails on the next run,
 * which is exactly the failure the binary wire format would otherwise hide.
 *
 *   cmake --build build --target test_viz
 *   ./build/bin/test_viz fixture /tmp/frame.bin
 *   VIZ_FIXTURE=/tmp/frame.bin npm test
 */
const path = process.env.VIZ_FIXTURE;

describe("wire format contract", () => {
  if (!path) {
    it.skip("needs VIZ_FIXTURE pointing at a generated frame", () => {});
    return;
  }

  const buf = readFileSync(path);
  const state = decodeState(
    buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength),
  );

  it("decodes the session fields the UI reads", () => {
    expect(state.seq).toBe(4242);
    expect(state.mode).toBe("selfplay");
    expect(state.running).toBe(true);
    expect(state.thinking).toBe(true);
    expect(state.nnueActive).toBe(true);
    expect(state.threads).toBe(2);
    expect(state.engineColor).toBe(1);
    expect(state.legalMoves).toEqual(["e2e4", "d2d4"]);
  });

  it("decodes game state", () => {
    expect(state.game.moves).toEqual(["e2e4", "e7e5", "g1f3"]);
    expect(state.game.lastMove).toBe("g1f3");
    expect(state.game.ply).toBe(3);
    expect(state.game.gameIndex).toBe(7);
    expect(state.game.wins).toBe(2);
    expect(state.game.draws).toBe(3);
    expect(state.game.losses).toBe(1);
    expect(state.game.over).toBe(false);
    expect(state.game.fen).toMatch(/ [wb] /);
    expect(state.game.startFen).toMatch(/ [wb] /);
  });

  it("decodes search telemetry", () => {
    expect(state.search.depth).toBe(11);
    expect(state.search.seldepth).toBe(17);
    expect(state.search.scoreCp).toBe(42);
    expect(state.search.nodes).toBe(123456);
    expect(state.search.tbHits).toBe(5);
    expect(state.search.elapsedMs).toBe(250);
    expect(state.search.nps).toBe(493824);
    expect(state.search.pv).toEqual(["d2d4", "d7d5", "c2c4"]);
    expect(state.search.negamaxTtHitRate).toBeCloseTo(58.25, 5);
    expect(state.search.qsearchTtHitRate).toBeCloseTo(31.5, 5);
  });

  it("decodes the candidate moves being compared", () => {
    const c = state.search.candidates;
    expect(c).toHaveLength(3);
    expect(c[0]).toEqual({ move: "d2d4", scoreCp: 42, pv: ["d2d4", "d7d5"] });
    expect(c[2].scoreCp).toBe(-7);
    // Ranked best first, which the UI relies on.
    for (let i = 1; i < c.length; i++)
      expect(c[i].scoreCp).toBeLessThanOrEqual(c[i - 1].scoreCp);
  });

  it("carries the architecture from the engine, not hard-coded here", () => {
    const a = state.arch;
    expect(a.hidden).toBe(1024);
    expect(a.pair).toBe(a.hidden / 2);
    expect(a.l1).toBe(16);
    expect(a.l2).toBe(32);
    expect(a.psqtBuckets).toBe(8);
    expect(a.kingBuckets).toBe(32);
    expect(a.pieceKinds).toBe(11);
    expect(a.features).toBe(a.kingBuckets * a.pieceKinds * 64);
    expect(a.actMax).toBe(127);
  });

  it("decodes every layer buffer at the right type and length", () => {
    const f = state.frame!;
    expect(f).not.toBeNull();
    const a = state.arch;
    expect(f.accUs).toBeInstanceOf(Int16Array);
    expect(f.accThem).toBeInstanceOf(Int16Array);
    expect(f.l1in).toBeInstanceOf(Uint8Array);
    expect(f.outContrib).toBeInstanceOf(Int32Array);
    expect(f.accUs.length).toBe(a.hidden);
    expect(f.accThem.length).toBe(a.hidden);
    expect(f.l1in.length).toBe(a.hidden);
    expect(f.l1out.length).toBe(a.l1);
    expect(f.l2out.length).toBe(a.l2);
    expect(f.outContrib.length).toBe(a.l2);
    expect(f.l2Contrib.length).toBe(a.l2 * a.l1);
    expect(f.l1Top.length).toBe(a.l1 * f.l1TopK * 2);
  });

  it("keeps activations inside their declared range", () => {
    const f = state.frame!;
    const max = state.arch.actMax;
    for (const arr of [f.l1in, f.l1out, f.l2out])
      for (const v of arr) expect(v).toBeGreaterThanOrEqual(0), expect(v).toBeLessThanOrEqual(max);
  });

  it("agrees with the engine's own arithmetic", () => {
    const f = state.frame!;
    // The identity the C++ side also asserts; if the decoder mis-slices a
    // buffer these stop reconciling.
    expect(f.eval).toBe(f.psqt + f.positional);
    expect(f.bucket).toBeGreaterThanOrEqual(0);
    expect(f.bucket).toBeLessThan(state.arch.psqtBuckets);
  });

  it("decodes active features with a valid feature index", () => {
    const f = state.frame!;
    const a = state.arch;
    expect(f.whiteFeatures.length).toBe(f.white.featureCount);
    expect(f.blackFeatures.length).toBe(f.black.featureCount);
    for (const side of [f.whiteFeatures, f.blackFeatures]) {
      for (const ft of side) {
        expect(ft.square).toBeGreaterThanOrEqual(0);
        expect(ft.square).toBeLessThan(64);
        expect(ft.featureIndex).toBeGreaterThanOrEqual(0);
        expect(ft.featureIndex).toBeLessThan(a.features);
        // The index must re-derive from its own reported parts.
        const bucket = side === f.whiteFeatures ? f.white.kingBucket : f.black.kingBucket;
        expect((bucket * a.pieceKinds + ft.pieceKind) * 64 + ft.orientedSquare).toBe(
          ft.featureIndex,
        );
      }
    }
  });
});
